Name:           ros-kinetic-jaguar-navigation
Version:        0.1.0
Release:        0%{?dist}
Summary:        ROS jaguar_navigation package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/jaguar
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-amcl
Requires:       ros-kinetic-base-local-planner
Requires:       ros-kinetic-dwa-local-planner
Requires:       ros-kinetic-frontier-exploration
Requires:       ros-kinetic-gmapping
Requires:       ros-kinetic-map-server
Requires:       ros-kinetic-move-base
Requires:       ros-kinetic-navfn
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-roslaunch

%description
Navigation package for DrRobot's Jaguar 4X4

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Mon Nov 28 2016 George Stavrinos <gstavrinos@iit.demokritos.gr> - 0.1.0-0
- Autogenerated by Bloom

